# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F690-6645";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=persist" ];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=snapshots" ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/fb9d6955-278f-4a4e-9f9e-dc536e01c8bc";
    fsType = "btrfs";
    options = [ "subvol=log" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a04a9e5a-bc3a-416c-bb84-aa48eea0ef0c"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20u2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
