# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["ehci_pci" "ahci" "xhci_pci" "firewire_ohci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=root"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF60-C63B";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=persist"];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=snapshots"];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/b109a417-be9c-48ad-ae9f-e24133ee9fc6";
    fsType = "btrfs";
    options = ["subvol=log"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/d3c78815-5207-4d41-80b8-9aae10e8a592";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
